#freemarker
spring: 
   freemarker:
      template-loader-path: classpath:/templates/
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html; charset=utf-8
      expose-request-attributes: true
      expose-session-attributes: true
## 获取contextPath (根路径
      request-context-attribute: request
      suffix: .ftl
#扫描mybatis
#mybatis: 
#  type-aliases-package: com.entity
#  mapper-locations: classpath:mapper/*.xml         